#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	myridwan
# //	Dscription: Xray Menu Management
# //	email: admin@myridwan.com
# //  telegram: https://t.me/kytxz
# //====================================================
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
OR='\033[1;93m'
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v ─insecure ─silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/arivpnstores/akses/main/ip"
CITY=$(cat /etc/xray/city)
PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/dns)
domain=$(cat /etc/xray/domain)
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "${OR}────────────────────────────────────────────${NC}"
    echo -e "\033[42m          ARISCTUNNEL AUTOSCRIPT          ${NC}"
    echo -e "${OR}────────────────────────────────────────────${NC}"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/ARI_VPN_STORE"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281327393959"
    echo -e "${OR}────────────────────────────────────────────${NC}"
    exit
  fi
}
checking_sc
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  clear
  echo -e "  ${OR}──────────────────────────────────────${NC}"
  echo -e " ${z}│$NC\033[41m     Add Xray/Vless Account               $NC│$NC" 
  echo -e "  ${OR}──────────────────────────────────────${NC}"
  echo ""
  read -rp "  Input Username: " -e user
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
    echo -e "  ${OR}──────────────────────────────────────${NC}"
    echo -e " ${z}│$NC\033[41m     Add Xray/Vless Account               $NC│$NC" 
    echo -e "  ${OR}──────────────────────────────────────${NC}"
    echo ""
    echo "       The customer name already exists"
    echo ""
    echo -e "  ${OR}───────────────────────────────────────${NC}"
    exit

  fi
done

uuid=$(cat /proc/sys/kernel/random/uuid)
sec=3
echo ""
spinner=(⣻ ⢿ ⡿ ⣟ ⣯ ⣷)
while [ $sec -gt 0 ]; do
  echo -ne "\e[33m ${spinner[sec]} Setting up a Premium Account $sec seconds...\r"
  sleep 1
  sec=$(($sec - 1))
done
clear
echo ""
echo -e "\e[1;32m   input dependecies account $user\e[0m\n"
echo -e "\033[0;33m .::.  Script by ARISCTUNNEL  .::.\e[0m\n"
echo ""
echo "   Setup Limit Quota/ip for Account"
echo "       0 For Unlimited/No Limit"
echo ""
echo "   Username : $user"
until [[ $masaaktif =~ ^[0-9]+$ ]]; do
  read -p "   Expired (days): " masaaktif
done
until [[ $Quota =~ ^[0-9]+$ ]]; do
  read -p "   Limit User (GB): " Quota
done
until [[ $iplim =~ ^[0-9]+$ ]]; do
  read -p "   Limit User (IP): " iplim
done
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"

cat >/var/www/html/vless-$user.txt <<-END

──────────────────────
# Format Vless WS (CDN)
──────────────────────

- name: Vless-$user-WS (CDN)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /whatever/vless
    headers:
      Host: ${domain}
──────────────────────
# Format Vless WS (CDN) Non TLS
──────────────────────
- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /whatever/vless
    headers:
      Host: ${domain}
  udp: true
──────────────────────
#  Format Vless gRPC (SNI)
──────────────────────
- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
  grpc-service-name: vless-grpc
  udp: true

──────────────────────
# Link Vless Account
──────────────────────
Link TLS      : 
${vlesslink1}
──────────────────────
Link none TLS : 
${vlesslink2}
──────────────────────
Link GRPC     : 
${vlesslink3}
──────────────────────

END

vlesslink1="vless://${uuid}@${domain}:443?path=/whatever/vless&security=tls&encryption=none&type=ws#${user}-WS-(CDN)-TLS"
vlesslink2="vless://${uuid}@${domain}:80?path=/whatever/vless&encryption=none&type=ws#${user}-WS-(CDN)-NTLS"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}-(SNI)-GRPC"
systemctl restart xray
if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi
#if [ -z ${iplim} ]; then
#  iplim="0"
#fi
if [ -z ${Quota} ]; then
  Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
#  echo "${iplim}" >/etc/vless/${user}IP
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp} ${uuid}" >>/etc/vless/.vless.db

clear -x
echo -e "${OR}───────────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "\e[92;1m    Xray/Vless Account    \E[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "${OR}───────────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Remarks     : ${user}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Host Server : ${domain}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Host XrayDNS: ${NS}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port DNS    : 443, 53" | tee -a /etc/xray/log-create-${user}.log
echo -e "port TLS    : 443" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port NTLS   : 80, 8080" | tee -a /etc/xray/log-create-${user}.log
echo -e "Network     : WS or gRPC" | tee -a /etc/xray/log-create-${user}.log
echo -e "ServiceName : vless-grpc" | tee -a /etc/xray/log-create-${user}.log
echo -e "Path        : /whatever/vless " | tee -a /etc/xray/log-create-${user}.log
echo -e "User ID     : ${uuid}" | tee -a /etc/xray/log-create-${user}.log
#echo -e "Pub Key     : ${PUB}" | tee -a /etc/xray/log-create-${user}.log
echo -e "${OR}───────────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Link TLS  : ${vlesslink1}" | tee -a /etc/xray/log-create-${user}.log
echo -e "${OR}───────────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Link NTLS : ${vlesslink2}" | tee -a /etc/xray/log-create-${user}.log
echo -e "${OR}───────────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Link GRPC : ${vlesslink3}" | tee -a /etc/xray/log-create-${user}.log
echo -e "${OR}───────────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Format OpenClash : https://${domain}:81/vless-$user.txt" | tee -a /etc/xray/log-create-${user}.log
echo -e "${OR}───────────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Expired On : $exp" | tee -a /etc/xray/log-create-${user}.log
echo -e "" | tee -a /etc/xray/log-create-${user}.log
exit 0
