#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	myridwan
# //	Dscription: Xray Menu Management
# //	email: admin@myridwan.com
# //  telegram: https://t.me/kytxz
# //====================================================
IP=$(curl -sS ipv4.icanhazip.com)
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
OR='\033[1;93m'
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v ─insecure ─silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/arivpnstores/akses/main/ip"
CITY=$(cat /etc/xray/city)
PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/dns)
domain=$(cat /etc/xray/domain)
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "${OR}────────────────────────────────────────────${NC}"
    echo -e "\033[42m          ARISCTUNNEL AUTOSCRIPT          ${NC}"
    echo -e "${OR}────────────────────────────────────────────${NC}"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/ARI_VPN_STORE"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281327393959"
    echo -e "${OR}────────────────────────────────────────────${NC}"
    exit
  fi
}
checking_sc
clear

echo -e "  ${OR}──────────────────────────────────────${NC}"
echo -e " ${z}│$NC\033[41m     Delete SSH Account               $NC│$NC" 
echo -e "  ${OR}──────────────────────────────────────${NC}"
echo ""
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/ssh/.ssh.db")
if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    echo ""
    echo "  No customer name available"
    echo ""
    exit 0
fi
echo ""
echo "     NO  USERNAME     EXPIRED"
echo "     ────────────────────────"
grep -E "^### " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2-3 | column -t | nl -s ') '
until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
    if [[ ${CLIENT_NUMBER} == '1' ]]; then
        read -rp "Select one client [1]: " CLIENT_NUMBER
    else
        echo ""
        until [[ $CLIENT_NUMBER =~ ^[0-9]+$ ]]; do
            read -rp "     Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
        done
        user=$(grep -E "^### " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
        exp=$(grep -E "^### " "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
        userdel -f $user
        sed -i "/^### $user/d" /etc/ssh/.ssh.db
        rm /etc/xray/log-createssh-$user.log
        clear
        echo "────────────────────────────────────────────────"
        echo -e "Delete SSH Account User ${grenbo}$user${NC} Successfully"
        echo -e "account has been permanently deleted"
        echo "────────────────────────────────────────────────"
        echo ""
        exit
    fi
done
