#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}─->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
g="\033[1;92m"
y="\033[96m" #yellow
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
export CHATID="1962241851"
export KEY="6814623012:AAH0n6J7iy8fkDE3MZghhmePj5wQpdwZpJ8"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v ─insecure ─silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/arivpnstores/akses/main/ip"
#data_ip="https://abc.xcodehoster.com/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/ARI_VPN_STORE"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281327393959"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear
echo -e " ${y}┌─────────────────────────────┐$NC"
echo -e " ${z}│$NC\033[41m    MENU TROJAN              $NC│$NC"
echo -e " ${y}└─────────────────────────────┘          $NC"
echo -e    "\033[1;93m  ┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${y}│${NC}${g} 1.${NC} \033[0;36m Creating Trojan Account${NC}"
echo -e "  ${y}│${NC}${g} 2.${NC} \033[0;36m Trial Trojan Account${NC}"
echo -e "  ${y}│${NC}${g} 3.${NC} \033[0;36m Delete Trojan Account${NC}"
echo -e "  ${y}│${NC}${g} 4.${NC} \033[0;36m Renew Trojan Account${NC}"
echo -e "  ${y}│${NC}${g} 5.${NC} \033[0;36m Check Trojan login Account${NC}"
echo -e "  ${y}│${NC}${g} 6.${NC} \033[0;36m Detail Trojan Account ${NC}"
echo -e "  ${y}│${NC}${g} x.${NC} \033[0;36m Exit Trojan Manager${NC}"
echo -e    "\033[1;93m  └──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 6 ] : " menu
case $menu in
1)
    addtr
    ;;
2)
    trialtr
    ;;
3)
    deltr
    ;;
4)
    renewtr
    ;;
5)
    cektr
    ;;
6)
    user-tr
    ;;    
0)
    menu
    ;;
esac
